/**
 * 用户可见文案字典（v0.2.0 i18n，最小实现）。
 * 语言选择：浏览器语言以 zh 开头用中文，其余用英文（缺省中文）。
 * 音色名/镜像源等数据标签不翻译（保持原样），仅 UI 文案入字典。
 */

const zh = {
  stateVoiceMode: '语音模式',
  ttsNoticeFail: '朗读连接失败：正在重试…',
  enterFail: '进入语音模式失败',
  disabled: '语音模式已禁用（插件 enabled=false）',
  sendFailKept: '发送失败，已保留在草稿',
  micDenied: '麦克风被拒绝：请在浏览器地址栏允许麦克风权限',
  micUnavailable: '麦克风不可用',
  hold: '按住',
  recognizing: '识别中…',
  holdToTalk: '按住说话',
  releaseToSend: '松开发送',
  voiceDetected: '语音中',
  entering: '进入中…',
  voiceBtn: '语音',
  ariaActive: '语音模式进行中',
  ariaEnter: '进入语音对话模式',
  titleHold: '语音模式进行中 · 按住说话、松手发送；短按退出；Esc/失去焦点放弃；Ctrl+Shift+V 退出',
  titleToggle: '语音模式进行中 · 点击退出（Ctrl+Shift+V）· 按住 Ctrl 立即发送',
  titleEnter: '进入语音对话模式（Ctrl+Shift+V）',
  loadingModel: '正在加载模型…',
  listening: '聆听中…',
  thinking: '思考中…',
  barHold: '语音模式 · 按住说话（短按退出）',
  barListening: '语音模式 · 聆听中…',
  wakeWord: '唤醒词',
  sayWake: '说「{wake}」开始',
  reading: '朗读中…',
  recognitionFail: '识别失败，请重试',
  sessionExpired: '语音会话已断开，正在重连…',
  sessionExpiredFail: '语音会话重连失败，请重新开启语音模式',
  modelDownloadFail: '语音模型下载失败（{file}）：请检查网络后重新进入语音模式重试',
  startFail: '语音模式启动失败：{err}',
  holdDots: '按住说话…',
  exit: '退出',
  skip: '跳过',
  configUnavailableNote: '（设置文档未就绪，面板就绪后会自动出现）。',
  // settings-form
  previewNameFirst: '请先填写音色名（ShortName）',
  previewDisabled: '语音模式已禁用（插件 enabled=false），无法试听',
  previewPlayFail: '试听失败：无法播放该音色',
  previewAutoplay: '浏览器拦截了自动播放，请再点一次试听',
  previewCheck: '试听失败：请检查网络或音色名（ShortName）是否正确',
  previewRateLimited: '试听太频繁了，稍候几秒再点（每分钟限 20 次）',
  previewTimeout: '合成超时：模型仍在加载，请稍候几秒再试',
  previewSynthesisFail: '合成失败',
  previewBtnTitle: '试听当前音色（当前语速）',
  synthesizing: '合成中…',
  preview: '试听',
  custom: '自定义',
  // settings rows
  voicePrev: '上一音色',
  voiceNext: '下一音色',
  modeBtnToggle: '持续聆听',
  modeBtnHold: '按住说',
  modeBtnTitle: '点击切换交互模式（保存到设置）',
  descVoice: 'Edge 云端音色（进入时自动加载微软全部音色，常用中文音色置顶，下拉或 ◀▶ 选；也可「自定义」填 ShortName）',
  descVoiceLocal: '本地音色（vits 五个说话人全部列出，下拉选或 ◀▶ 切换；无需自定义）',
  ttsEngine: '朗读引擎',
  descTtsEngine: '本地 VITS（纯中文）/ 本地 Kokoro（中英均可）/ Edge 云端（音质最自然，文本上微软）/ Azure 云端（付费，支持音素级多音字）',
  engineVits: '本地 VITS',
  engineKokoro: '本地中英',
  engineEdge: 'Edge 云端',
  engineAzure: 'Azure 云端（付费）',
  descVoiceAzure: 'Azure 音色（与 Edge 同名 ShortName，沿用下方音色选择；文本发送到你的 Azure 语音资源）',
  descAzureEndpoint: 'Azure 语音资源端点：填区域名（如 eastasia）或完整链接（https://<region>.tts.speech.microsoft.com）',
  descAzureKeyRef: 'Azure 密钥的凭据引用名（如 AZURE_SPEECH_KEY）；真实密钥写进 DSH 凭据库，配置文件只留引用名',
  descAzureSecret: '在下方粘贴 Azure 订阅密钥并保存：宿主写入 DSH 凭据库，明文不落配置文件',
  descAzurePhonemes: '多音字拼音表：每行「词 => 拼音」（如 行 => hang2、银行 => yin2 hang2），# 起首为注释；经 SSML <phoneme> 精确发音，仅 Azure 引擎生效',
  descUsageStats: '语音改编站调用外部改写模型累计消耗的 token（仅进程内累计，重启清零）',
  usageRequests: '请求',
  usagePrompt: '输入',
  usageCompletion: '输出',
  usageTotal: '合计',
  usageReset: '清零',
  descVoiceKokoro: 'Kokoro 中英音色（103 个全部列出，下拉选或 ◀▶ 切换；48-51 中文名，其余按编号+实测性别标注，中英混读均可）',
  descRate: '朗读语速倍率（0.5 慢速 ～ 2.0 快速，1.0 正常）',
  descInterrupt: '发声打断灵敏度（0 高门槛 / 1 中 / 2 低；发声确认约 0.3/0.2/0.1 秒）',
  descBargeIn: '打断方式（auto 自动打断：开口即打断，耳机/安静环境推荐；manual 手动打断：外放推荐——回声不会误触发自打断，按住麦克风/Ctrl 显式打断）',
  bargeInAuto: '自动',
  bargeInManual: '手动',
  descEchoGate: '回声门控阈值（dB，默认 6）：自动打断要求残差高于回声地板此值；外放仍误打断调大（8~10），太难打断调小（3~4）',
  descShortcut: '进入/退出语音模式的快捷键（形如 Ctrl+Shift+V；留空禁用快捷键，只用麦克风按钮；避免浏览器保留组合如 Ctrl+W/N/T）',
  vadDetected: 'VAD 检测到语音',
  aecOff: '原生回声消除未生效',
  aecOffHint: '浏览器原生回声消除未生效（外放可能自打断），建议用耳机或切换「手动打断」',
  interruptConfirm: '打断确认',
  sev0: '0 高门槛',
  sev1: '1 中',
  sev2: '2 低',
  descSilence: '说完整一句的静音停顿毫秒数（默认 1500 毫秒，给思考停顿留空间；至少 250ms 语音才判句，防短促噪声误触发）',
  descIdle: '无活动自动退出语音模式的分钟数（默认 10；0 = 禁用。朗读与回合推进都会重置计时）',
  descModelHost: 'ASR 模型下载源（官方源 / 国内镜像，或选「自定义」填任意镜像）',
  descAutoSend: '静音到点自动发送（连续多段拼成一条；关=只进草稿；按住 Ctrl / hold 松手仍发送）',
  descAutoResume: '切换回上次语音会话时自动恢复语音模式（默认关，需麦克风权限已授予；省去每次切换会话后重新点麦克风）',
  descSpokenFormat: '语音会话注入排版与公式提示词（保留完整 Markdown 与 LaTeX 排版，并要求字面美元符号转义为 \\$；默认关，改动即时生效）',
  descRewriteEnabled: '语音改编站总开关（默认关）：开启后公式/表格/代码先改写成口播稿再朗读；正文朗读不受影响。开启前不改动任何现有行为。',
  descRewriteBaseUrl: '改写模型 OpenAI 兼容端点（默认智谱 GLM）。请求从宿主发出，密钥不上浏览器。',
  descRewriteApiKeyRef: '改写模型密钥的凭据引用：填环境变量名（如 GLM_API_KEY）。密钥不写入配置文件明文。',
  descRewriteSecret: '在下方输入框粘贴 API 密钥并点「保存到凭据库」：宿主写入 DSH 凭据存储，设置文件只保留上面的引用名，明文不落配置。',
  descRewriteModel: '改写模型名（默认 glm-4.5-air）。',
  descRewriteTimeout: '改写请求超时毫秒（默认 8000）；超时自动回退确定性读法。',
  descRewriteMaxTokens: '改写输出 token 基线（默认 400）：插件会按片段长度自动上调（上限 2048），避免长表格/多符号时 JSON 被截断而回退。',
  descRewriteTemperature: '改写温度（默认 0，越低越稳定）。',
  descRewriteCache: '相同片段复用讲稿（默认开，减少重复请求）。',
  descRewriteDisableThinking: '关闭改写模型的思考链（默认开）：GLM-4.5 等思考型模型不关思考会只输出推理、正文为空，迫使改写回退；仅端点支持 thinking 参数时有效。',
  descRewriteContextChars: '传给改写模型的前文字符上限（默认 800）：实际长度按片段动态伸缩——短公式少给前文，大代码块/大表格多给，并总是从整句开始。0 = 不给前文，只保留已确认的符号表。',
  descPronunciationEnabled: '启用多音字用户词表（默认开）。关 = 完全不改任何朗读文本；屏幕显示本来就不受影响。',
  descPronunciationFixes: '多音字用户词表（可增删/清空）：每行「原词 => 同音替身」，替身必须与原词等字数；只纠正读音，不允许增删字或改成同义词，格式/字数不符的行会被忽略并回报。原词也可写成正则 /pattern/flags（例：/第\\s*(\\d+)\\s*行/ => 第$1航，用于「第 N 行」这类动态上下文；此时跳过等字数校验，正则由你自负风险）。默认值是一份「行(háng)」同音词表，不是隐藏内置，随时可改。',
  descGuardMode: '改写守卫强度：standard 默认 / lenient 放宽（更难触发回退，但复述/重复朗读风险更高）/ strict 收紧 / off 全关（只保留 JSON 协议解析，读到指令文本等风险自负）。',
  guardModeOff: '全关',
  guardModeLenient: '放宽',
  guardModeStandard: '标准',
  guardModeStrict: '严格',
  descGuardAllowRules: '守卫放行规则（每行一条，# 注释）：整行写 /正则/flags → 命中「改写稿」即放行；加 seg: 前缀 → 命中「原始片段」，该片段跳过全部守卫；其它写法按字面文字做子串匹配。用于把守卫误杀的读法放行（放行后直接采用模型输出，不再做长度/复述/数字校验）。',
  descWholeSentenceMath: '含行内公式的整句交给模型出稿（默认开）：整句一次成型，正文和公式不会各念一遍，根治重复朗读。关掉则退回「公式片段单独改写 + 正文单独念」，长句容易重复。仅 mathMode=model 时生效。',
  descBlockPause: '段落之间的停顿毫秒（默认 350；0 = 关闭）。标题之后用 1.6 倍；解决「换段、标题到正文没有停顿、一口气念完」的不自然。仅语音改编站开启时生效。',
  descMathMode: '数学朗读模式：确定性规则零容错（默认）/ 交给改写模型 / 原样念出。',
  mathModeRules: '确定性规则',
  mathModeModel: '交给模型',
  mathModeVerbatim: '原样念出',
  descSenseVoice: '定稿用 SenseVoice 重译（带标点 + 数字归一化、识别更准；默认开。关闭可省 228MB 模型，只走流式识别）',
  descToolBeep: '工具调用提示音（默认关）：AI 思考/调用工具时"滴"一声；嫌吵就保持关闭',
  descMode: '交互模式（toggle 持续聆听+静音断句 / hold 按住说话）',
  modeToggle: '持续聆听',
  modeHold: '按住说话',
  descWakeWord: '唤醒词（默认关；如「你好小D」，说出后开始识别）',
  wakePlaceholder: '如：你好小D',
  settingsCardDesc: '朗读引擎 / 音色 / 语速 / 打断灵敏度 / 打断方式 / 静音停顿 / 空闲超时 / 模型镜像 / 自动发送 / 交互模式 / 唤醒词 / 口语化提示词',
  settingsEffectiveNote: '朗读引擎 / 音色 / 语速 / 模型精度 / 口语化提示词 / 重译 即时生效；其余（打断灵敏度 / 打断方式 / 回声门控 / 快捷键 / 静音 / 空闲 / 镜像 / 自动发送 / 自动恢复 / 交互模式 / 唤醒词 / 工具提示音）下次进入语音模式时生效。',
  configUnavailable: '配置暂不可用',
  // telemetry（P1-5 开发模式延迟埋点状态条：各段耗时标签）
  telUtteranceEnd: '说完',
  telEndpoint: '端点',
  telSubmitted: '定稿',
  telFirstToken: '首Token',
  telFirstSentence: '首句',
  telFirstChunk: '首chunk',
  telFirstPlayed: '首音',
  // 模型管理（设置面板实时状态/重试）
  modelsTitle: '语音模型',
  modelsDisabled: '已关闭（设置中开启）',
  modelStreamingAsr: '流式识别',
  modelVad: '端点 VAD',
  modelSense: '定稿重译',
  modelsReady: '就绪',
  modelsDownloading: '{file} {percent}%',
  modelsFail: '下载失败（{sec} 秒后自动重试）',
  modelsMissing: '未下载',
  modelsRetry: '重试下载',
  modelsRetrying: '重试中…',
  modelsRetryHint: '镜像切换或下载失败后点击立即重试',
  modelsHint: '下载/进度实时跟进；失败自动退避 60s 重试。镜像源切换后点「重试下载」立即生效；也可用 npm run prefetch 预下载。',
  // 朗读引擎状态（设置面板内联展示）
  engineLoading: '加载中…',
  engineReady: '就绪',
  engineError: '加载失败',
  engineIdle: '可试听',
  ttsModelsMissing: '本地模型未就绪',
  ttsRedownload: '重新下载',
  ttsRedownloadHint: '清理该引擎模型缓存并重新下载',
  ttsCleaning: '清理中…',
  ttsDownload: '下载',
  ttsDelete: '删除',
  ttsDownloading: '下载中…',
  ttsDeleting: '删除中…',
  ttsDownloadHint: '下载该引擎的本地模型；下载完成后立即就绪，可试听/朗读',
  ttsDeleteHint: '删除本地模型（释放空间；下次使用会自动重新下载）',
  kokoroModel: 'Kokoro 模型精度',
  kokoroModelInt8: 'int8（默认）',
  kokoroModelFp32: 'fp32（音质更好）',
  descKokoroModel: 'Kokoro 模型精度：int8 体积小/加载快（纯 CPU 服务器或低带宽推荐，默认）；fp32 音质更好但约 311MB、更慢（有独立显卡或大内存机器推荐）。两档共用同一套 103 音色，切换即时生效。',
  // 设置分组标题
  secRead: '朗读与音色',
  secInterrupt: '打断与静音',
  secInteraction: '交互与输入',
  secRecognition: '识别与口语',
  secAdaptation: '语音改编站',
  secModel: '模型与镜像',
  telTotal: '合计',
} as const

const en: Record<keyof typeof zh, string> = {
  stateVoiceMode: 'Voice Mode',
  ttsNoticeFail: 'Read-aloud connection lost: retrying…',
  enterFail: 'Failed to enter voice mode',
  disabled: 'Voice mode disabled (plugin enabled=false)',
  sendFailKept: 'Send failed; text kept in draft',
  micDenied: 'Microphone denied: allow mic access for this site',
  micUnavailable: 'Microphone unavailable',
  hold: 'Hold',
  recognizing: 'Recognizing…',
  holdToTalk: 'Hold to talk',
  releaseToSend: 'Release to send',
  voiceDetected: 'Voice active',
  entering: 'Entering…',
  voiceBtn: 'Voice',
  ariaActive: 'Voice mode active',
  ariaEnter: 'Enter voice mode',
  titleHold: 'Voice mode · hold to talk, release to send; tap to exit; Esc/blur cancels; Ctrl+Shift+V exits',
  titleToggle: 'Voice mode · click to exit (Ctrl+Shift+V) · hold Ctrl to send now',
  titleEnter: 'Enter voice mode (Ctrl+Shift+V)',
  loadingModel: 'Loading model…',
  listening: 'Listening…',
  thinking: 'Thinking…',
  barHold: 'Voice mode · hold to talk (tap to exit)',
  barListening: 'Voice mode · listening…',
  wakeWord: 'Wake word',
  sayWake: 'Say "{wake}" to start',
  reading: 'Reading…',
  recognitionFail: 'Recognition failed, try again',
  sessionExpired: 'Voice session expired, reconnecting…',
  sessionExpiredFail: 'Voice session reconnect failed; please re-enter voice mode',
  modelDownloadFail: 'Model download failed ({file}): check network and re-enter voice mode',
  startFail: 'Voice mode failed to start: {err}',
  holdDots: 'Hold to talk…',
  exit: 'Exit',
  skip: 'Skip',
  configUnavailableNote: ' (settings document not ready; the panel will appear when it is).',
  previewNameFirst: 'Enter a voice ShortName first',
  previewDisabled: 'Voice mode disabled; preview unavailable',
  previewPlayFail: 'Preview failed: cannot play this voice',
  previewAutoplay: 'Autoplay blocked — click preview again',
  previewCheck: 'Preview failed: check network or ShortName',
  previewRateLimited: 'Preview too frequent — wait a few seconds (20/min limit)',
  previewTimeout: 'Synthesis timed out: model still loading, retry in a few seconds',
  previewSynthesisFail: 'Synthesis failed',
  previewBtnTitle: 'Preview voice (current rate)',
  synthesizing: 'Synthesizing…',
  preview: 'Preview',
  custom: 'Custom',
  voicePrev: 'Previous voice',
  voiceNext: 'Next voice',
  modeBtnToggle: 'Continuous',
  modeBtnHold: 'Hold to talk',
  modeBtnTitle: 'Click to switch interaction mode (saved to settings)',
  descVoice: 'Edge cloud voices (auto-loads all Microsoft voices; common Chinese voices pinned on top; ◀▶ or dropdown; custom ShortName allowed)',
  descVoiceLocal: 'Local voice (vits, all 5 speakers listed; dropdown or ◀▶; no custom needed)',
  ttsEngine: 'Read-aloud engine',
  descTtsEngine: 'Local VITS (Chinese only) / Local Kokoro (Chinese + English) / Edge cloud (most natural, text sent to Microsoft) / Azure cloud (paid, phoneme-level polyphone control)',
  engineVits: 'Local VITS',
  engineKokoro: 'Local zh-en',
  engineEdge: 'Edge cloud',
  engineAzure: 'Azure cloud (paid)',
  descVoiceAzure: 'Azure voice (same ShortName as Edge; text is sent to your Azure Speech resource)',
  descAzureEndpoint: 'Azure Speech endpoint: region name (e.g. eastasia) or full URL (https://<region>.tts.speech.microsoft.com)',
  descAzureKeyRef: 'Credential reference name for the Azure key (e.g. AZURE_SPEECH_KEY); the secret is stored in the DSH credential store, never in config',
  descAzureSecret: 'Paste the Azure subscription key below and save: the host stores it in the DSH credential store; the settings file keeps only the reference name',
  descAzurePhonemes: 'Polyphone table: one rule per line, "word => pinyin" (e.g. 行 => hang2, 银行 => yin2 hang2); # starts a comment. Applied via SSML <phoneme>, Azure engine only',
  descUsageStats: 'Cumulative tokens consumed by the speech adaptation station external rewrite model (in-memory only; resets on restart)',
  usageRequests: 'Requests',
  usagePrompt: 'Prompt',
  usageCompletion: 'Completion',
  usageTotal: 'Total',
  usageReset: 'Reset',
  descVoiceKokoro: 'Kokoro zh-en voices (103; ◀▶ to cycle; 48-51 named Chinese, others numbered with measured gender; mixed zh-en supported)',
  descRate: 'Speech rate (0.5 slow – 2.0 fast, 1.0 normal)',
  descInterrupt: 'Interrupt sensitivity (0 high barrier / 1 medium / 2 low; ~0.3/0.2/0.1 s speech confirmation)',
  descBargeIn: 'Barge-in mode (auto: interrupt by speaking — headphones/quiet; manual: for loudspeaker, no echo-triggered self-interrupt — hold mic/Ctrl to interrupt)',
  bargeInAuto: 'Auto',
  bargeInManual: 'Manual',
  descEchoGate: 'Echo gate threshold (dB, default 6): auto barge-in requires the residual to exceed the echo floor by this value; raise (8-10) if speaker echo still interrupts, lower (3-4) if hard to interrupt',
  descShortcut: 'Shortcut to enter/exit voice mode (e.g. Ctrl+Shift+V; empty disables it, mic button only; avoid browser-reserved combos like Ctrl+W/N/T)',
  vadDetected: 'VAD speech',
  aecOff: 'Native AEC off',
  aecOffHint: 'Native echo cancellation is not active (speaker echo may self-interrupt); use headphones or Manual barge-in',
  interruptConfirm: 'interrupt confirm',
  sev0: '0 high',
  sev1: '1 medium',
  sev2: '2 low',
  descSilence: 'Silence pause before a sentence is committed (default 1500 ms; at least 250 ms of speech required, guards against noise triggers)',
  descIdle: 'Auto-exit voice mode after this many idle minutes (default 10; 0 = disabled; playback and turn activity reset the timer)',
  descModelHost: 'ASR model download source (official source / mirror, or any custom URL)',
  descAutoSend: 'Auto-send once quiet (consecutive segments join into one message; off = draft only; Ctrl / hold still sends)',
  descAutoResume: 'Auto-resume voice mode when switching back to the last voice session (default off, requires granted mic permission)',
  descSpokenFormat: 'Inject formatting & formula guidance into voice replies (keep full Markdown/LaTeX; escape literal dollar signs as \\$; default off, live)',
  descRewriteEnabled: 'Speech adaptation master switch (default off): rewrite formulas/tables/code into spoken scripts before reading; normal prose is unaffected.',
  descRewriteBaseUrl: 'OpenAI-compatible endpoint for the rewrite model (default Zhipu GLM). Requests are sent from the host; the key never reaches the browser.',
  descRewriteApiKeyRef: 'Credential reference for the rewrite key: an environment-variable name (e.g. GLM_API_KEY). The secret is never written to config.',
  descRewriteSecret: 'Paste the API key below and click Save: the host stores it in the DSH credential store; the settings file keeps only the reference name above.',
  descRewriteModel: 'Rewrite model name (default glm-4.5-air).',
  descRewriteTimeout: 'Rewrite request timeout in ms (default 8000); on timeout it falls back to deterministic reading.',
  descRewriteMaxTokens: 'Baseline output tokens for rewriting (default 400): raised automatically with segment size (cap 2048) so long tables/symbol lists do not truncate the JSON and force a fallback.',
  descRewriteTemperature: 'Rewrite temperature (default 0, lower is more stable).',
  descRewriteCache: 'Reuse the script for identical fragments (default on; fewer requests).',
  descRewriteDisableThinking: 'Disable the rewrite model thinking chain (default on): thinking models like GLM-4.5 otherwise emit only reasoning with empty content, forcing a fallback. Only effective when the endpoint supports the thinking parameter.',
  descRewriteContextChars: 'Upper bound of preceding prose sent to the rewrite model (default 800). The actual size scales dynamically with the segment: short formulas get little prose, large code blocks/tables get more, always starting at a sentence boundary. 0 = no prose, symbol table only.',
  descPronunciationEnabled: 'Enable the user pronunciation word list (default on). Off = no spoken text is changed at all; the on-screen text is never affected.',
  descPronunciationFixes: 'User pronunciation word list (edit or clear freely): one entry per line, term => same-length homophone. Only pronunciation is corrected; adding/removing characters or using a synonym is rejected and reported. The term may also be a regex /pattern/flags (e.g. /第\\s*(\\d+)\\s*行/ => 第$1航 for dynamic contexts such as row numbers); regex entries skip the length check and are used at your own risk. The default value is a "行(háng)" homophone list, not a hidden built-in.',
  descGuardMode: 'Rewrite guard strength: standard (default) / lenient (rarely falls back, higher risk of echo or repeated reading) / strict / off (only JSON protocol parsing remains; reading instruction text back is at your own risk).',
  guardModeOff: 'Off',
  guardModeLenient: 'Lenient',
  guardModeStandard: 'Standard',
  guardModeStrict: 'Strict',
  descGuardAllowRules: 'Guard allow rules (one per line, # comment): a bare /regex/flags line matches the rewritten speech; a seg: prefix matches the original segment (that whole segment skips all guards); anything else is a literal substring match on the speech. Use it to allow readings the guards wrongly rejected (allowed output is used as-is, with no length/echo/number checks).',
  descWholeSentenceMath: 'Hand any sentence containing inline math to the model as a whole (default on): the sentence is produced once, so prose and formulas are never read twice — this is the structural fix for repeated reading. Turn off to fall back to per-formula rewriting plus separate prose. Only effective when mathMode=model.',
  descBlockPause: 'Silence inserted between paragraphs in ms (default 350; 0 = off). Headings use 1.6x; fixes the unnatural feel of paragraphs and heading-to-body running on with no pause. Only applies while the speech adaptation station is on.',
  descMathMode: 'Math reading mode: deterministic rules (default, zero-tolerance) / let the rewrite model handle it / read verbatim.',
  mathModeRules: 'Deterministic rules',
  mathModeModel: 'Let the model',
  mathModeVerbatim: 'Verbatim',
  descSenseVoice: 'Re-transcribe the finalized utterance with SenseVoice (punctuation + ITN, more accurate; default on — turn off to skip the 228 MB model and keep streaming only)',
  descToolBeep: 'Tool-call beep (default off): beep when the agent is thinking/calling tools; keep off if it annoys you',
  descMode: 'Interaction mode (toggle: continuous listen + auto-send / hold: press to talk)',
  modeToggle: 'Continue listen',
  modeHold: 'Hold to talk',
  descWakeWord: 'Wake word (default off; e.g. Hey D)',
  wakePlaceholder: 'e.g. Hey D',
  settingsCardDesc: 'Engine / voice / rate / interrupt / barge-in / silence / idle / model host / auto-send / mode / wake word / spoken format',
  settingsEffectiveNote: 'Engine / voice / rate / model precision / spoken format / re-transcribe apply immediately; the rest (interrupt / barge-in / echo gate / shortcut / silence / idle / mirror / auto-send / auto-resume / mode / wake word / tool beep) apply next time you enter voice mode.',
  configUnavailable: 'Configuration unavailable',
  telUtteranceEnd: 'end',
  telEndpoint: 'endpoint',
  telSubmitted: 'submit',
  telFirstToken: '1st token',
  telFirstSentence: '1st sentence',
  telFirstChunk: '1st chunk',
  telFirstPlayed: '1st audio',
  modelsTitle: 'Voice models',
  modelsDisabled: 'off (enable in settings)',
  modelStreamingAsr: 'Streaming ASR',
  modelVad: 'Endpoint VAD',
  modelSense: 'Finalize',
  modelsReady: 'Ready',
  modelsDownloading: '{file} {percent}%',
  modelsFail: 'Download failed (auto-retry in {sec}s)',
  modelsMissing: 'not downloaded',
  modelsRetry: 'Retry',
  modelsRetrying: 'Retrying…',
  modelsRetryHint: 'Click to retry now after switching mirror or a failure',
  modelsHint: 'Live download state; failures auto-backoff 60s. After switching the mirror, click Retry to take effect immediately; npm run prefetch pre-downloads.',
  engineLoading: 'loading…',
  engineReady: 'ready',
  engineError: 'failed',
  engineIdle: 'ready to preview',
  ttsModelsMissing: 'local models missing',
  ttsRedownload: 'Re-download',
  ttsRedownloadHint: 'Clear this engine model cache and re-download',
  ttsCleaning: 'Clearing…',
  ttsDownload: 'Download',
  ttsDelete: 'Delete',
  ttsDownloading: 'Downloading…',
  ttsDeleting: 'Deleting…',
  ttsDownloadHint: "Download this engine's local model; becomes ready immediately after",
  ttsDeleteHint: 'Delete local models (frees space; auto re-downloads on next use)',
  kokoroModel: 'Kokoro model precision',
  kokoroModelInt8: 'int8 (default)',
  kokoroModelFp32: 'fp32 (better quality)',
  descKokoroModel: 'Kokoro model precision: int8 is smaller/faster (CPU server or low bandwidth; default); fp32 sounds better but ~311MB and slower (GPU or large memory). Both share the same 103 voices; switches live.',
  secRead: 'Reading & voice',
  secInterrupt: 'Interrupt & silence',
  secInteraction: 'Interaction',
  secRecognition: 'Recognition & speech',
  secAdaptation: 'Speech adaptation',
  secModel: 'Model & mirror',
  telTotal: 'total',
}

/**
 * 语言判定：**以 dsh 为准**——dsh 的语言设置（Settings → General → Language，
 * locale 命名空间，未设置时回退浏览器）解析后写入 <html lang>，页面加载时即已生效；
 * 插件不再自行探测浏览器语言。切换语言后按「刷新页面」生效（与 README 一致）。
 */
/** 每次调用时解析（组件渲染时 dsh 已写入最终 <html lang>），无缓存/无时序竞态。 */
const guess = (): 'zh' | 'en' =>
  /^zh\b/i.test(
    (typeof document !== 'undefined' && document.documentElement.lang) ||
      (typeof navigator !== 'undefined' ? navigator.language : '') ||
      '',
  )
    ? 'zh'
    : 'en'

/** 文案键类型（供组件侧声明含 t() 键的结构化配置）。 */
export type TKey = keyof typeof zh

export const t = (key: TKey): string => (guess() === 'zh' ? zh[key] : en[key] ?? zh[key])
