/**
 * 用户可见文案字典（最小 i18n）。
 * 语言选择：dsh 写入的 <html lang> 以 zh 开头用中文，其余用英文。
 * 音色名/镜像源等数据标签不翻译。
 */

const zh = {
  // 通用
  stateVoiceMode: '语音朗读',
  buildLabel: '语音朗读',
  // 朗读总开关（原麦克风按钮位置）
  readToggle: '朗读',
  readToggleOn: '关闭自动朗读',
  readToggleOff: '开启自动朗读',
  readTitleOn: '自动朗读中：AI 每轮新回复会自动朗读，新回复会打断上一条；点击关闭',
  readTitleOff: '开启自动朗读：此后 AI 每轮新回复自动朗读（新回复会打断上一条）',
  // 每条回复的朗读键
  readOne: '朗读',
  readOneTitle: '朗读这条回复',
  readOneEmpty: '这条回复暂无可朗读文字',
  // 状态条
  readPlaying: '朗读中…',
  readStop: '停止',
  readFail: '朗读失败：请检查网络或朗读引擎设置',
  ttsNoticeFail: '朗读连接失败：正在重试…',
  configUnavailable: '配置暂不可用',
  configUnavailableNote: '（设置文档未就绪，面板就绪后会自动出现）。',
  // 设置面板
  settingsCardDesc: '朗读引擎 / 音色 / 语速 / 数学朗读模式 / 语音改编站',
  settingsEffectiveNote: '朗读引擎 / 音色 / 语速 / 模型精度 / 排版提示词 即时生效；自动朗读开关在输入框旁按钮中随时切换。',
  secRead: '朗读与音色',
  secAdaptation: '语音改编站',
  // 设置行标签
  ttsEngine: '朗读引擎',
  descTtsEngine: '本地 VITS（纯中文）/ 本地 Kokoro（中英均可）/ Edge 云端（音质最自然，文本上微软）/ Azure 云端（付费，支持音素级多音字）',
  engineVits: '本地 VITS',
  engineKokoro: '本地中英',
  engineEdge: 'Edge 云端',
  engineAzure: 'Azure 云端（付费）',
  kokoroModel: 'Kokoro 模型精度',
  kokoroModelInt8: 'int8（默认）',
  kokoroModelFp32: 'fp32（音质更好）',
  descKokoroModel: 'Kokoro 模型精度：int8 体积小/加载快（纯 CPU 服务器或低带宽推荐，默认）；fp32 音质更好但约 311MB、更慢（有独立显卡或大内存机器推荐）。两档共用同一套 103 音色，切换即时生效。',
  descVoice: 'Edge 云端音色（进入时自动加载微软全部音色，常用中文音色置顶，下拉或 ◀▶ 选；也可「自定义」填 ShortName）',
  descVoiceLocal: '本地音色（vits 五个说话人全部列出，下拉选或 ◀▶ 切换；无需自定义）',
  descVoiceKokoro: 'Kokoro 中英音色（103 个全部列出，下拉选或 ◀▶ 切换；48-51 中文名，其余按编号+实测性别标注，中英混读均可）',
  descVoiceAzure: 'Azure 音色（与 Edge 同名 ShortName，沿用下方音色选择；文本发送到你的 Azure 语音资源）',
  descRate: '朗读语速倍率（0.5 慢速 ～ 2.0 快速，1.0 正常）',
  descSpokenFormat: '自动朗读会话注入排版与公式提示词（保留完整 Markdown 与 LaTeX 排版，并要求字面美元符号转义为 \\$；默认关，改动即时生效）',
  voicePrev: '上一音色',
  voiceNext: '下一音色',
  custom: '自定义',
  preview: '试听',
  synthesizing: '合成中…',
  previewBtnTitle: '试听当前音色（当前语速）',
  previewNameFirst: '请先填写音色名（ShortName）',
  previewDisabled: '语音朗读已禁用（插件 enabled=false），无法试听',
  previewPlayFail: '试听失败：无法播放该音色',
  previewAutoplay: '浏览器拦截了自动播放，请再点一次试听',
  previewCheck: '试听失败：请检查网络或音色名（ShortName）是否正确',
  previewRateLimited: '试听太频繁了，稍候几秒再点（每分钟限 20 次）',
  previewTimeout: '合成超时：模型仍在加载，请稍候几秒再试',
  previewSynthesisFail: '合成失败',
  // Azure
  descAzureEndpoint: 'Azure 语音资源端点：填区域名（如 eastasia）或完整链接（https://<region>.tts.speech.microsoft.com）',
  descAzureKeyRef: 'Azure 密钥的凭据引用名（如 AZURE_SPEECH_KEY）；真实密钥写进 DSH 凭据库，配置文件只留引用名',
  descAzureSecret: '在下方粘贴 Azure 订阅密钥并保存：宿主写入 DSH 凭据库，明文不落配置文件',
  descAzurePhonemes: '多音字拼音表：每行「词 => 拼音」（如 行 => hang2、银行 => yin2 hang2），# 起首为注释；经 SSML <phoneme> 精确发音，仅 Azure 引擎生效',
  // 改编站
  descRewriteEnabled: '语音改编站总开关（默认关）：开启后公式/表格/代码先改写成口播稿再朗读；正文朗读不受影响。开启前不改动任何现有行为。',
  descRewriteBaseUrl: '改写模型 OpenAI 兼容端点（默认智谱 GLM）。请求从宿主发出，密钥不上浏览器。',
  descRewriteApiKeyRef: '改写模型密钥的凭据引用：填环境变量名（如 GLM_API_KEY）。密钥不写入配置文件明文。',
  descRewriteSecret: '在下方输入框粘贴 API 密钥并点「保存到凭据库」：宿主写入 DSH 凭据存储，设置文件只保留上面的引用名，明文不落配置。',
  descRewriteModel: '改写模型名（默认 glm-4.5-air）。',
  descRewriteTimeout: '改写请求超时毫秒（默认 8000）；超时自动回退确定性读法。',
  descRewriteMaxTokens: '改写输出 token 基线（默认 400）：插件会按片段长度自动上调（上限 2048），避免长表格/多符号时 JSON 被截断而回退。',
  descRewriteTemperature: '改写温度（默认 0，越低越稳定）。',
  descRewriteCache: '相同片段复用讲稿（默认开，减少重复请求）。',
  descRewriteDisableThinking: '关闭改写模型的思考链（默认开）：GLM-4.5 等思考型模型不关思考会只输出推理、正文为空，迫使改写回退；仅端点支持 thinking 参数时有效。',
  descRewriteContextChars: '传给改写模型的前文字符上限（默认 800）：实际长度按片段动态伸缩——短公式少给前文，大代码块/大表格多给，并总是从整句开始。0 = 不给前文，只保留已确认的符号表。',
  descPronunciationEnabled: '启用多音字用户词表（默认开）。关 = 完全不改任何朗读文本；屏幕显示本来就不受影响。',
  descPronunciationFixes: '多音字用户词表（可增删/清空）：每行「原词 => 同音替身」，替身必须与原词等字数；只纠正读音，不允许增删字或改成同义词，格式/字数不符的行会被忽略并回报。原词也可写成正则 /pattern/flags（例：/第\\s*(\\d+)\\s*行/ => 第$1航，用于「第 N 行」这类动态上下文；此时跳过等字数校验，正则由你自负风险）。默认值是一份「行(háng)」同音词表，不是隐藏内置，随时可改。',
  descGuardMode: '改写守卫强度：standard 默认 / lenient 放宽（更难触发回退，但复述/重复朗读风险更高）/ strict 收紧 / off 全关（只保留 JSON 协议解析，读到指令文本等风险自负）。',
  guardModeOff: '全关',
  guardModeLenient: '放宽',
  guardModeStandard: '标准',
  guardModeStrict: '严格',
  descGuardAllowRules: '守卫放行规则（每行一条，# 注释）：整行写 /正则/flags → 命中「改写稿」即放行；加 seg: 前缀 → 命中「原始片段」，该片段跳过全部守卫；其它写法按字面文字做子串匹配。用于把守卫误杀的读法放行（放行后直接采用模型输出，不再做长度/复述/数字校验）。',
  descWholeSentenceMath: '含行内公式的整句交给模型出稿（默认开）：整句一次成型，正文和公式不会各念一遍，根治重复朗读。关掉则退回「公式片段单独改写 + 正文单独念」，长句容易重复。仅 mathMode=model 时生效。',
  descBlockPause: '段落之间的停顿毫秒（默认 350；0 = 关闭）。标题之后用 1.6 倍；解决「换段、标题到正文没有停顿、一口气念完」的不自然。仅语音改编站开启时生效。',
  descMathMode: '数学朗读模式：确定性规则零容错（默认）/ 交给改写模型 / 原样念出。',
  mathModeRules: '确定性规则',
  mathModeModel: '交给模型',
  mathModeVerbatim: '原样念出',
  // 用量统计
  descUsageStats: '语音改编站调用外部改写模型累计消耗的 token（仅进程内累计，重启清零）',
  usageRequests: '请求',
  usagePrompt: '输入',
  usageCompletion: '输出',
  usageTotal: '合计',
  usageReset: '清零',
  // 引擎/模型状态
  engineLoading: '加载中…',
  engineReady: '就绪',
  engineError: '加载失败',
  engineIdle: '可试听',
  ttsModelsMissing: '本地模型未就绪',
  ttsRedownload: '重新下载',
  ttsRedownloadHint: '清理该引擎模型缓存并重新下载',
  ttsCleaning: '清理中…',
  ttsDownload: '下载',
  ttsDelete: '删除',
  ttsDownloading: '下载中…',
  ttsDeleting: '删除中…',
  ttsDownloadHint: '下载该引擎的本地模型；下载完成后立即就绪，可试听/朗读',
  ttsDeleteHint: '删除本地模型（释放空间；下次使用会自动重新下载）',
} as const

const en: Record<keyof typeof zh, string> = {
  stateVoiceMode: 'Read Aloud',
  buildLabel: 'Read Aloud',
  readToggle: 'Read',
  readToggleOn: 'Turn off auto read-aloud',
  readToggleOff: 'Turn on auto read-aloud',
  readTitleOn: 'Auto read-aloud is on: every new assistant reply is read, and a new reply interrupts the previous one. Click to turn off.',
  readTitleOff: 'Turn on auto read-aloud: every new assistant reply will be read (a new reply interrupts the previous one).',
  readOne: 'Read',
  readOneTitle: 'Read this reply aloud',
  readOneEmpty: 'This reply has no readable text',
  readPlaying: 'Reading…',
  readStop: 'Stop',
  readFail: 'Read-aloud failed: check the network or the engine settings',
  ttsNoticeFail: 'Read-aloud connection lost: retrying…',
  configUnavailable: 'Configuration unavailable',
  configUnavailableNote: ' (settings document not ready; the panel will appear when it is).',
  settingsCardDesc: 'Engine / voice / rate / math mode / speech adaptation station',
  settingsEffectiveNote: 'Engine / voice / rate / model precision / formatting prompt apply immediately; toggle auto read-aloud from the button beside the composer.',
  secRead: 'Reading & voice',
  secAdaptation: 'Speech adaptation',
  ttsEngine: 'Read-aloud engine',
  descTtsEngine: 'Local VITS (Chinese only) / Local Kokoro (Chinese + English) / Edge cloud (most natural, text sent to Microsoft) / Azure cloud (paid, phoneme-level polyphone control)',
  engineVits: 'Local VITS',
  engineKokoro: 'Local zh-en',
  engineEdge: 'Edge cloud',
  engineAzure: 'Azure cloud (paid)',
  kokoroModel: 'Kokoro model precision',
  kokoroModelInt8: 'int8 (default)',
  kokoroModelFp32: 'fp32 (better quality)',
  descKokoroModel: 'Kokoro model precision: int8 is smaller/faster (CPU server or low bandwidth; default); fp32 sounds better but ~311MB and slower (GPU or large memory). Both share the same 103 voices; switches live.',
  descVoice: 'Edge cloud voices (auto-loads all Microsoft voices; common Chinese voices pinned on top; ◀▶ or dropdown; custom ShortName allowed)',
  descVoiceLocal: 'Local voice (vits, all 5 speakers listed; dropdown or ◀▶; no custom needed)',
  descVoiceKokoro: 'Kokoro zh-en voices (103; ◀▶ to cycle; 48-51 named Chinese, others numbered with measured gender; mixed zh-en supported)',
  descVoiceAzure: 'Azure voice (same ShortName as Edge; text is sent to your Azure Speech resource)',
  descRate: 'Speech rate (0.5 slow – 2.0 fast, 1.0 normal)',
  descSpokenFormat: 'Inject formatting & formula guidance into auto-read replies (keep full Markdown/LaTeX; escape literal dollar signs as \\$; default off, live)',
  voicePrev: 'Previous voice',
  voiceNext: 'Next voice',
  custom: 'Custom',
  preview: 'Preview',
  synthesizing: 'Synthesizing…',
  previewBtnTitle: 'Preview voice (current rate)',
  previewNameFirst: 'Enter a voice ShortName first',
  previewDisabled: 'Read-aloud disabled; preview unavailable',
  previewPlayFail: 'Preview failed: cannot play this voice',
  previewAutoplay: 'Autoplay blocked — click preview again',
  previewCheck: 'Preview failed: check network or ShortName',
  previewRateLimited: 'Preview too frequent — wait a few seconds (20/min limit)',
  previewTimeout: 'Synthesis timed out: model still loading, retry in a few seconds',
  previewSynthesisFail: 'Synthesis failed',
  descAzureEndpoint: 'Azure Speech endpoint: region name (e.g. eastasia) or full URL (https://<region>.tts.speech.microsoft.com)',
  descAzureKeyRef: 'Credential reference name for the Azure key (e.g. AZURE_SPEECH_KEY); the secret is stored in the DSH credential store, never in config',
  descAzureSecret: 'Paste the Azure subscription key below and save: the host stores it in the DSH credential store; the settings file keeps only the reference name',
  descAzurePhonemes: 'Polyphone table: one rule per line, "word => pinyin" (e.g. 行 => hang2, 银行 => yin2 hang2); # starts a comment. Applied via SSML <phoneme>, Azure engine only',
  descRewriteEnabled: 'Speech adaptation master switch (default off): rewrite formulas/tables/code into spoken scripts before reading; normal prose is unaffected.',
  descRewriteBaseUrl: 'OpenAI-compatible endpoint for the rewrite model (default Zhipu GLM). Requests are sent from the host; the key never reaches the browser.',
  descRewriteApiKeyRef: 'Credential reference for the rewrite key: an environment-variable name (e.g. GLM_API_KEY). The secret is never written to config.',
  descRewriteSecret: 'Paste the API key below and click Save: the host stores it in the DSH credential store; the settings file keeps only the reference name above.',
  descRewriteModel: 'Rewrite model name (default glm-4.5-air).',
  descRewriteTimeout: 'Rewrite request timeout in ms (default 8000); on timeout it falls back to deterministic reading.',
  descRewriteMaxTokens: 'Baseline output tokens for rewriting (default 400): raised automatically with segment size (cap 2048) so long tables/symbol lists do not truncate the JSON and force a fallback.',
  descRewriteTemperature: 'Rewrite temperature (default 0, lower is more stable).',
  descRewriteCache: 'Reuse the script for identical fragments (default on; fewer requests).',
  descRewriteDisableThinking: 'Disable the rewrite model thinking chain (default on): thinking models like GLM-4.5 otherwise emit only reasoning with empty content, forcing a fallback. Only effective when the endpoint supports the thinking parameter.',
  descRewriteContextChars: 'Upper bound of preceding prose sent to the rewrite model (default 800). The actual size scales dynamically with the segment: short formulas get little prose, large code blocks/tables get more, always starting at a sentence boundary. 0 = no prose, symbol table only.',
  descPronunciationEnabled: 'Enable the user pronunciation word list (default on). Off = no spoken text is changed at all; the on-screen text is never affected.',
  descPronunciationFixes: 'User pronunciation word list (edit or clear freely): one entry per line, term => same-length homophone. Only pronunciation is corrected; adding/removing characters or using a synonym is rejected and reported. The term may also be a regex /pattern/flags; regex entries skip the length check and are used at your own risk. The default value is a "行(háng)" homophone list, not a hidden built-in.',
  descGuardMode: 'Rewrite guard strength: standard (default) / lenient (rarely falls back, higher risk of echo or repeated reading) / strict / off (only JSON protocol parsing remains; reading instruction text back is at your own risk).',
  guardModeOff: 'Off',
  guardModeLenient: 'Lenient',
  guardModeStandard: 'Standard',
  guardModeStrict: 'Strict',
  descGuardAllowRules: 'Guard allow rules (one per line, # comment): a bare /regex/flags line matches the rewritten speech; a seg: prefix matches the original segment (that whole segment skips all guards); anything else is a literal substring match on the speech.',
  descWholeSentenceMath: 'Hand any sentence containing inline math to the model as a whole (default on): the sentence is produced once, so prose and formulas are never read twice. Only effective when mathMode=model.',
  descBlockPause: 'Silence inserted between paragraphs in ms (default 350; 0 = off). Headings use 1.6x. Only applies while the speech adaptation station is on.',
  descMathMode: 'Math reading mode: deterministic rules (default, zero-tolerance) / let the rewrite model handle it / read verbatim.',
  mathModeRules: 'Deterministic rules',
  mathModeModel: 'Let the model',
  mathModeVerbatim: 'Verbatim',
  descUsageStats: 'Cumulative tokens consumed by the speech adaptation station external rewrite model (in-memory only; resets on restart)',
  usageRequests: 'Requests',
  usagePrompt: 'Prompt',
  usageCompletion: 'Completion',
  usageTotal: 'Total',
  usageReset: 'Reset',
  engineLoading: 'loading…',
  engineReady: 'ready',
  engineError: 'failed',
  engineIdle: 'ready to preview',
  ttsModelsMissing: 'local models missing',
  ttsRedownload: 'Re-download',
  ttsRedownloadHint: 'Clear this engine model cache and re-download',
  ttsCleaning: 'Clearing…',
  ttsDownload: 'Download',
  ttsDelete: 'Delete',
  ttsDownloading: 'Downloading…',
  ttsDeleting: 'Deleting…',
  ttsDownloadHint: "Download this engine's local model; becomes ready immediately after",
  ttsDeleteHint: 'Delete local models (frees space; auto re-downloads on next use)',
}

const guess = (): 'zh' | 'en' =>
  /^zh\b/i.test(
    (typeof document !== 'undefined' && document.documentElement.lang) ||
      (typeof navigator !== 'undefined' ? navigator.language : '') ||
      '',
  )
    ? 'zh'
    : 'en'

export type TKey = keyof typeof zh

export const t = (key: TKey): string => (guess() === 'zh' ? zh[key] : en[key] ?? zh[key])
